org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.234
neo_version_range=[21.1.169,)
loader_version_range=[1,)

mod_version=1.21.1-26.9.1-neoforge
mod_id=fastnbt
mod_name=Fast NBT
mod_authors=nutant233
mod_url=https://github.com/nutant233/Fast-NBT/
mod_description=Improve nbt operational performance
mod_issue_tracker=https://github.com/nutant233/Fast-NBT/issues/
mod_license=LGPL-3.0
